#!/usr/bin/perl

    # po2texi: Convert a .po file back to .texi after applying msgmerge
    # Copyright (C) {2017}  {Gunter Königsmann}

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Skip everything until the first blank line
while (my $line = <>) {
    last if $line =~ /^$/;
}

print "\@c This file has been autogenerated from a .po file containing translations.\n";

$snippetline = "";
$snippet = "";
$msgid = "";
$msgstr = "";
    
# Now work through the whole file
while (my $line = <>) {

    # Handle lines containing text
    if ($line =~ /^".*"$/)
    {
	$snippetline = $line;
	$snippetline =~ s/^"(.*)"$/\1/g;
	$snippetline =~ s/\\n$//g;
	$snippet.= $snippetline;
    }
    
    if ($line =~ /^msgstr +""$/)
    {
	$msgid = $snippet;
	$snippet = "";
    }

    if (($line =~ /^msgid +""$/) || ($line =~ /^$/))
    {
	$msgstr = $snippet;
	if ($msgstr eq "")
	{
	    $msgstr = $msgid;
	}
	if ($msgstr ne "")
	{
	    print $msgstr;
	}

	$msgid = "";
	$msgstr = "";
	$snippet = "";
    }
}

# Print the last translation if the file didn't end in a newline.
if ($msgstr eq "")
{
    $msgstr = $msgid;
}
if ($msgstr ne "")
{
    print $msgstr;
}

